name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.img }}
    strategy:
      matrix:
        include:
            - { os:  ubuntu-latest, img: "python:3.12-slim", python: "3.12", toxenv: py312, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, img: "python:3.12-slim",                 toxenv:  lint, cache: ~/.cache/pip }

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        if: ${{ matrix.img == '' }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v4
        id: cache-pip
        with:
          path: ${{ matrix.cache }}
          key: ${{ matrix.os }}-${{ matrix.python }}-pip

      - name: Setup container cache ownership
        if: ${{ matrix.img != '' }}
        run: |
          mkdir -p ~/.cache
          chown -R $(id -u) ~/.cache

      - name: Install dependencies
        run: python -m pip install --upgrade tox

      - name: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
