name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1

    - name: pip cache environment
      uses: actions/cache@v1
      id:   cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: run tox
      run: |
        tox
