name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install theme and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Build documentation
        run: |
          cd Documentation
          sphinx-build -b dirhtml . _build/html -E -a

      - name: Update Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd Documentation

          echo "synchronizing new content..."
          git worktree add gh-pages gh-pages
          rsync -av --delete --exclude '.git' --exclude '.doctrees' \
            _build/html/ gh-pages/
          cd gh-pages
          git add -A

          if [ -n "$(git status --porcelain)" ]; then
              git config --local user.email "noreply@jdknight.me"
              git config --local user.name "GitHub Action"
              git commit -a -m "update"

              echo "adjusting url..."
              git remote set-url --push origin \
                https://jdknight:$GITHUB_TOKEN@github.com/jdknight/sphinx-alice-theme
              echo "pushing new content..."
              git push origin gh-pages
              echo "done"
          else
              echo "no new changes"
          fi
